### ISSUE TITLE
3. 문서화

### ISSUE THREAD

**Issue by thejsw** [Soongsil-Developers/22sdc-blog-team2#3]
- [x] 3-1. 스웨거에 대한 조사
- [x] 3-2. vite에 대한 조사
- [x] 3-3. npm, yarn에 대한 조사
- [x] 3-4. recoil에 대한 조사
- [x] 3-5. netlify에 대한 조사
- [x] 3-6. gitignore에 대한 조사

선택사항
- markdown에 대한 조사
- 그라운드룰에 대한 조사
- 깃허브 기능 조사

**Comment by 00kang** [comment]
<b>스웨거에 대한 조사</b>

- 스웨거는 WEB API 문서화를 위한 도구이다.
- [스웨거 홈페이지](http://%28https//swagger.io)에서는 스웨거를 OAS(Open API Specification)이라고 소개하고 있다.
- 말 그대로 API들이 가지는 명세(Spec)을 관리하기 위한 프로젝트이다.
> 백 엔드 프로그램과 프론트 엔드 프로그램 사이에서 정확히 어떠한 방식으로 데이터를 구조 받을 지에 대한 명세가 필요할 수 있습니다. 이러한 내용이 담긴 문서를 일반적으로 API 명세서
출처: https://ndb796.tistory.com/249 [안경잡이개발자:티스토리]
- Web API를 수동으로 문서화 하는 것은 굉장히 힘든일인데, Web API의 스펙이 변경되었을 때 문서 역시 변경되어야 하는데 이를 유지하는 것이 쉽지 않다. Swagger를 사용하면 Web API가 수정되더라도 문서가 자동으로 갱신 되기 때문에 편리하다.

출처: https://codingnotes.tistory.com/42 [코딩수첩:티스토리]
*** 
<b>RealWorld Swagger</b>
https://api.realworld.io/api-docs/

**Comment by thejsw** [comment]
# vite에 대한 조사

## 웹팩
- 웹팩은 오픈 소스 자바스크립트 모듈 번들러로써 여러개로 나누어져 있는 파일들을 하나의 자바스크립트 코드로 압축하고 최적화하는 라이브러리입니다.

- 모듈 번들러는 다음과 같은 장점이 있습니다.
1. 여러 파일의 자바스크립트 코드를 압축하여 최적화 할 수 있기 때문에 로딩에 대한 네트워크 비용을 줄일 수 있습니다.
2. 모듈 단위로 개발이 가능하여, 가독성과 유지보수가 쉽습니다.
3. 최신 자바스크립트 문법을 지원하지 않는 브라우저에서 사용할 수 있는 코드로 쉽게 변환시켜 줍니다.

***

## vite
-  빠르고 간결한 모던 웹 프로젝트 개발 경험에 초점을 맞춰 탄생한 빌드 도구입니다.

#### Vite를 사용해야 하는 이유
> 브라우저에서 ESM(ES Modules)을 지원하기 전까지는, JavaScript 모듈화를 네이티브 레벨에서 진행할 수 없었습니다. 
> 따라서 개발자들은 "번들링(Bundling)*"이라는 우회적인 방법을 사용할 수 밖에 없었죠. 
> (* 번들링: 모듈화된 소스 코드를 브라우저에서 실행할 수 있는 파일로 한데 묶어 연결해주는 작업)
> 자바스크립트 코드 수가 증가하면서, 서버 구동에 걸리는 시간이 느려졌습니다.

- vite는 이 문제를 dependencies 그리고 source code 두 가지 카테고리로 나누어 개발 서버를 시작하도록 함으로써 해결했죠.
- 느렸던 소스 코드 갱신, 배포 시에 필요한 번들링 과정을 위해서 vite를 사용해야 합니다.

***

<b>Vite를 사용해야 하는 이유</b>
https://vitejs-kr.github.io/guide/why.html#the-problems

**Comment by gomjellie** [comment]
@thejsw @00kang 

해당 이슈에 comment를 추가하는 방식이 아닌, 별도 이슈로 생성해서 진행해주시길 바랍니다

**Comment by 00kang** [comment]
@gomjellie 
네 알겠습니다!
