### ISSUE TITLE
3-8. jsdoc에 대한 조사

### ISSUE THREAD

**Issue by thejsw** [Soongsil-Developers/22sdc-blog-team2#36]
# JSDoc을 사용하여 자바스크립트에 타입 힌트 제공하기

## JSDoc

- [JSDoc](https://jsdoc.app/)은 자바스크립트 API 문서 생성기다. 자바스크립트 소스코드에 JSDoc 형식의 주석을 추가하면 API를 설명하는 HTML 문서를 생성할 수 있다. JSDoc 주석은 /** ... */ 사이에 기술한다. 일반적인 자바스크립트 주석 /* ... */은 무시된다.
- JSDoc는 js 파일 내 주석을 사용하여 코드를 작성하고 인터페이스를 설명하는 문서를 생성할 수 있다.
[JSDoc을 사용하여 자바스크립트에 타입 힌트 제공하기](https://poiemaweb.com/jsdoc-type-hint)

## JSDoc 설치 및 사용법
1. JSDoc 설치: npm i -D jsdoc
2. 디렉토리에 jsdoc.json 파일 생성
3. package.json 파일 수정
4. doc 명령어 수행: npm run doc

- @param은 매개변수 이름을 추가할 수 있고 매개변수는 이름을 대괄호로 감싸서 선택적 매개변수임을 명시할 수 있다.
[JSDoc 설치 및 사용법](https://geniee.tistory.com/28).

**Comment by gomjellie** [comment]
@thejsw 

// @ts-check 라는게 있군요 허허... 덕분에 하나 배워갑니다 :)

@ts-check를 쓰면 타입스크립트도 추가적으로 좀 공부해야할거에요~
조금씩 적용 부탁해요~
